name: Ejecutar Scraper Diario

on:
  schedule:
    - cron: "0 8 * * *" # Ejecuta todos los días a las 8 AM UTC
  workflow_dispatch: # Permite ejecutarlo manualmente desde GitHub Actions

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Instalar dependencias
        run: |
          pip install requests beautifulsoup4

      - name: Ejecutar el scraper
        run: python scrapperProductsJSON.py
