name: Ejecutar Scraper Diario

on:
  schedule:
    - cron: "0 8 * * *" # Ejecuta todos los días a las 8 AM UTC
  workflow_dispatch: # Permite ejecutarlo manualmente desde GitHub Actions

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Instalar dependencias
        run: |
          pip install requests beautifulsoup4

      - name: Ejecutar el scraper
        run: python scrapperProductsJSON.py

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Agregar y confirmar cambios
        run: |
          git add resultados_*.json
          git commit -m "Añadir resultados diarios [Automático]"
          git push origin main
